#!/usr/bin/env python3.14
"""Generate ``pycore_firmware/compiler/tables.py`` (compiler_design.md W-6).

One source of truth: ``pycore/targets/pycore.json`` plus the host ``opcode``
and ``keyword`` modules. Output is checked in; CI asserts regeneration is a
no-op. The file is subset-legal (plain ``dict`` / ``list`` literals).
"""

from __future__ import annotations

import argparse
import json
import keyword
import opcode
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_CATALOG = ROOT / "pycore" / "targets" / "pycore.json"
DEFAULT_OUTPUT = ROOT / "pycore_firmware" / "compiler" / "tables.py"

EMIT_SUPPORT = frozenset({"execute", "partial", "strip"})
# Decode no-ops that never appear as named catalog entries (pycore.json
# groups them under interpreter plumbing) but every co_code stream uses.
PLUMBING_OPS = ("CACHE", "EXTENDED_ARG")


def catalog_opnames(catalog: dict, *, levels: frozenset[str]) -> list[str]:
    names: list[str] = []
    opcodes = catalog.get("opcodes")
    if not isinstance(opcodes, dict):
        raise ValueError("pycore.json: missing opcodes object")
    for name, spec in opcodes.items():
        if not isinstance(spec, dict):
            continue
        if spec.get("support") in levels:
            names.append(name)
    return names


def execute_opnames(catalog: dict) -> list[str]:
    return sorted(catalog_opnames(catalog, levels=frozenset({"execute"})))


def emit_opnames(catalog: dict) -> list[str]:
    names = catalog_opnames(catalog, levels=EMIT_SUPPORT)
    for name in PLUMBING_OPS:
        if name not in names:
            names.append(name)
    return sorted(names)


def build_opmap(opnames: list[str]) -> dict[str, int]:
    missing = [name for name in opnames if name not in opcode.opmap]
    if missing:
        raise ValueError(
            "execute-level ops missing from host opcode.opmap: "
            + ", ".join(missing)
        )
    return {name: int(opcode.opmap[name]) for name in opnames}


def build_keywords() -> dict[str, int]:
    return {word: 1 for word in sorted(keyword.kwlist)}


def _format_int_dict(name: str, mapping: dict[str, int]) -> str:
    lines = [f"{name} = {{"]
    for key in mapping:
        lines.append(f"    {key!r}: {mapping[key]!r},")
    lines.append("}")
    return "\n".join(lines)


def _format_str_list(name: str, values: list[str]) -> str:
    lines = [f"{name} = ["]
    for value in values:
        lines.append(f"    {value!r},")
    lines.append("]")
    return "\n".join(lines)


def generate_tables_text(catalog_path: pathlib.Path | None = None) -> str:
    path = pathlib.Path(catalog_path) if catalog_path is not None else DEFAULT_CATALOG
    catalog = json.loads(path.read_text(encoding="utf-8"))
    emit_ops = emit_opnames(catalog)
    execute_ops = execute_opnames(catalog)
    opmap = build_opmap(emit_ops)
    keywords = build_keywords()
    chunks = [
        "# Generated by pycore/tools/gen_compiler_tables.py from",
        "# pycore/targets/pycore.json and the host opcode/keyword modules.",
        "# Do not edit. CI: pycore/tests/test_compiler_tables_fresh.py",
        "",
        _format_int_dict("OPMAP", opmap),
        "",
        _format_str_list("EMIT_OPS", emit_ops),
        "",
        _format_str_list("EXECUTE_OPS", execute_ops),
        "",
        _format_int_dict("KEYWORDS", keywords),
        "",
    ]
    return "\n".join(chunks)


def write_tables(
    output: pathlib.Path | None = None,
    *,
    catalog: pathlib.Path | None = None,
) -> pathlib.Path:
    dest = pathlib.Path(output) if output is not None else DEFAULT_OUTPUT
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(generate_tables_text(catalog), encoding="utf-8")
    return dest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--catalog",
        type=pathlib.Path,
        default=DEFAULT_CATALOG,
        help="Path to pycore.json (default: pycore/targets/pycore.json)",
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=DEFAULT_OUTPUT,
        help="Destination tables.py (default: pycore_firmware/compiler/tables.py)",
    )
    args = parser.parse_args(argv)
    write_tables(args.output, catalog=args.catalog)
    return 0


if __name__ == "__main__":
    sys.exit(main())
