#!/usr/bin/env python3
"""Generate the constant tables of pycore_fp_pow (float ** float).

The unit evaluates x ** y = 2 ** (y * log2 x) with shift-and-add digit
recurrences.  Both recurrences consume the constants

    CPOS[k] =  log2(1 + 2^-k) * 2^k
    CNEG[k] = -log2(1 - 2^-k) * 2^k          (k >= 1)

normalised so their leading one is in the units place; the datapath shifts
them right by the digit index.  They are stored as unsigned fixed point
with 2 integer and FW fraction bits (CNEG[1] = 2.0 exactly).

Writes pycore/rtl/pycore_fp_pow_rom.svh (a case-statement ROM function)
and pycore/tb/pow_rom.h (the same values for the DPI-C reference model).
Run from the repository root:  python3 pycore/tools/gen_pow_rom.py
"""
from decimal import Decimal, getcontext
from pathlib import Path

FW = 88           # fraction bits  (keep in sync with pycore_fp_pow.sv)
KMAX = 136        # entries k = 0 .. KMAX-1 (k = 0 unused, stored as 0)

getcontext().prec = 80
LN2 = Decimal(2).ln()
ONE = Decimal(1)
TWO = Decimal(2)


def q(v: Decimal) -> int:
    return int((v * (TWO ** FW)).to_integral_value())


def cpos(k: int) -> int:
    return q((ONE + TWO ** (-k)).ln() / LN2 * (TWO ** k)) if k else 0


def cneg(k: int) -> int:
    return q(-((ONE - TWO ** (-k)).ln()) / LN2 * (TWO ** k)) if k else 0


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    w = FW + 2
    pos = [cpos(k) for k in range(KMAX)]
    neg = [cneg(k) for k in range(KMAX)]
    assert all(v < (1 << w) for v in pos + neg)

    sv = [
        "// Generated by pycore/tools/gen_pow_rom.py -- do not edit.",
        "//",
        "// Constants of pycore_fp_pow: CPOS[k] = log2(1 + 2^-k) * 2^k and",
        "// CNEG[k] = -log2(1 - 2^-k) * 2^k, unsigned fixed point with 2 integer",
        f"// and {FW} fraction bits, rounded to nearest.",
        "`ifndef PYCORE_FP_POW_ROM_SVH",
        "`define PYCORE_FP_POW_ROM_SVH",
        "",
        f"localparam int PY_POW_ROM_FW   = {FW};",
        f"localparam int PY_POW_ROM_KMAX = {KMAX};",
        "",
        f"function automatic logic [{w - 1}:0] pycore_pow_rom(input logic neg, input logic [7:0] k);",
        "    unique case ({neg, k})",
    ]
    for k in range(KMAX):
        sv.append(f"        {{1'b0, 8'd{k:<3}}}: pycore_pow_rom = {w}'h{pos[k]:0{(w + 3) // 4}X};")
    for k in range(KMAX):
        sv.append(f"        {{1'b1, 8'd{k:<3}}}: pycore_pow_rom = {w}'h{neg[k]:0{(w + 3) // 4}X};")
    sv += [
        f"        default: pycore_pow_rom = {w}'d0;",
        "    endcase",
        "endfunction",
        "",
        "`endif",
        "",
    ]
    (root / "rtl" / "pycore_fp_pow_rom.svh").write_text("\n".join(sv))

    def c_pair(v: int) -> str:
        return f"{{0x{v >> 64:016X}ull, 0x{v & ((1 << 64) - 1):016X}ull}}"

    ch = [
        "// Generated by pycore/tools/gen_pow_rom.py -- do not edit.",
        "// Constants of pycore_fp_pow as {high 64, low 64} bit halves.",
        "#ifndef PYCORE_POW_ROM_H",
        "#define PYCORE_POW_ROM_H",
        f"#define POW_ROM_FW   {FW}",
        f"#define POW_ROM_KMAX {KMAX}",
        "static const unsigned long long pow_rom_pos[POW_ROM_KMAX][2] = {",
    ]
    ch += [f"    {c_pair(v)}," for v in pos]
    ch += ["};", "static const unsigned long long pow_rom_neg[POW_ROM_KMAX][2] = {"]
    ch += [f"    {c_pair(v)}," for v in neg]
    ch += ["};", "#endif", ""]
    (root / "tb" / "pow_rom.h").write_text("\n".join(ch))


if __name__ == "__main__":
    main()
