# Generated by pycore/tools/gen_compiler_tables.py from
# pycore/targets/pycore.json and the host opcode/keyword/token/ast modules.
# Do not edit. CI: pycore/tests/test_compiler_tables_fresh.py

OPMAP = {
    'BINARY_OP': 44,
    'BINARY_SLICE': 1,
    'BUILD_LIST': 46,
    'BUILD_MAP': 47,
    'BUILD_SET': 48,
    'BUILD_STRING': 50,
    'BUILD_TUPLE': 51,
    'CACHE': 0,
    'CALL': 52,
    'CALL_FUNCTION_EX': 4,
    'CALL_INTRINSIC_1': 53,
    'CALL_KW': 55,
    'CHECK_EXC_MATCH': 6,
    'COMPARE_OP': 56,
    'CONTAINS_OP': 57,
    'CONVERT_VALUE': 58,
    'COPY': 59,
    'COPY_FREE_VARS': 60,
    'DELETE_ATTR': 61,
    'DELETE_FAST': 63,
    'DELETE_SUBSCR': 8,
    'DICT_MERGE': 66,
    'DICT_UPDATE': 67,
    'END_FOR': 9,
    'EXTENDED_ARG': 69,
    'FORMAT_SIMPLE': 12,
    'FOR_ITER': 70,
    'GET_ITER': 16,
    'IS_OP': 74,
    'JUMP_BACKWARD': 75,
    'JUMP_FORWARD': 77,
    'LIST_APPEND': 78,
    'LIST_EXTEND': 79,
    'LOAD_ATTR': 80,
    'LOAD_CONST': 82,
    'LOAD_DEREF': 83,
    'LOAD_FAST': 84,
    'LOAD_FAST_AND_CLEAR': 85,
    'LOAD_FAST_BORROW': 86,
    'LOAD_FAST_BORROW_LOAD_FAST_BORROW': 87,
    'LOAD_FAST_CHECK': 88,
    'LOAD_FAST_LOAD_FAST': 89,
    'LOAD_GLOBAL': 92,
    'LOAD_NAME': 93,
    'LOAD_SMALL_INT': 94,
    'MAKE_CELL': 97,
    'MAKE_FUNCTION': 23,
    'MAP_ADD': 98,
    'NOP': 27,
    'NOT_TAKEN': 28,
    'POP_EXCEPT': 29,
    'POP_ITER': 30,
    'POP_JUMP_IF_FALSE': 100,
    'POP_JUMP_IF_NONE': 101,
    'POP_JUMP_IF_NOT_NONE': 102,
    'POP_JUMP_IF_TRUE': 103,
    'POP_TOP': 31,
    'PUSH_EXC_INFO': 32,
    'PUSH_NULL': 33,
    'RAISE_VARARGS': 104,
    'RERAISE': 105,
    'RESUME': 128,
    'RETURN_VALUE': 35,
    'SET_ADD': 107,
    'SET_FUNCTION_ATTRIBUTE': 108,
    'SET_UPDATE': 109,
    'STORE_ATTR': 110,
    'STORE_DEREF': 111,
    'STORE_FAST': 112,
    'STORE_FAST_LOAD_FAST': 113,
    'STORE_FAST_STORE_FAST': 114,
    'STORE_GLOBAL': 115,
    'STORE_NAME': 116,
    'STORE_SUBSCR': 38,
    'SWAP': 117,
    'TO_BOOL': 39,
    'UNARY_INVERT': 40,
    'UNARY_NEGATIVE': 41,
    'UNARY_NOT': 42,
    'UNPACK_EX': 118,
    'UNPACK_SEQUENCE': 119,
}

EMIT_OPS = [
    'BINARY_OP',
    'BINARY_SLICE',
    'BUILD_LIST',
    'BUILD_MAP',
    'BUILD_SET',
    'BUILD_STRING',
    'BUILD_TUPLE',
    'CACHE',
    'CALL',
    'CALL_FUNCTION_EX',
    'CALL_INTRINSIC_1',
    'CALL_KW',
    'CHECK_EXC_MATCH',
    'COMPARE_OP',
    'CONTAINS_OP',
    'CONVERT_VALUE',
    'COPY',
    'COPY_FREE_VARS',
    'DELETE_ATTR',
    'DELETE_FAST',
    'DELETE_SUBSCR',
    'DICT_MERGE',
    'DICT_UPDATE',
    'END_FOR',
    'EXTENDED_ARG',
    'FORMAT_SIMPLE',
    'FOR_ITER',
    'GET_ITER',
    'IS_OP',
    'JUMP_BACKWARD',
    'JUMP_FORWARD',
    'LIST_APPEND',
    'LIST_EXTEND',
    'LOAD_ATTR',
    'LOAD_CONST',
    'LOAD_DEREF',
    'LOAD_FAST',
    'LOAD_FAST_AND_CLEAR',
    'LOAD_FAST_BORROW',
    'LOAD_FAST_BORROW_LOAD_FAST_BORROW',
    'LOAD_FAST_CHECK',
    'LOAD_FAST_LOAD_FAST',
    'LOAD_GLOBAL',
    'LOAD_NAME',
    'LOAD_SMALL_INT',
    'MAKE_CELL',
    'MAKE_FUNCTION',
    'MAP_ADD',
    'NOP',
    'NOT_TAKEN',
    'POP_EXCEPT',
    'POP_ITER',
    'POP_JUMP_IF_FALSE',
    'POP_JUMP_IF_NONE',
    'POP_JUMP_IF_NOT_NONE',
    'POP_JUMP_IF_TRUE',
    'POP_TOP',
    'PUSH_EXC_INFO',
    'PUSH_NULL',
    'RAISE_VARARGS',
    'RERAISE',
    'RESUME',
    'RETURN_VALUE',
    'SET_ADD',
    'SET_FUNCTION_ATTRIBUTE',
    'SET_UPDATE',
    'STORE_ATTR',
    'STORE_DEREF',
    'STORE_FAST',
    'STORE_FAST_LOAD_FAST',
    'STORE_FAST_STORE_FAST',
    'STORE_GLOBAL',
    'STORE_NAME',
    'STORE_SUBSCR',
    'SWAP',
    'TO_BOOL',
    'UNARY_INVERT',
    'UNARY_NEGATIVE',
    'UNARY_NOT',
    'UNPACK_EX',
    'UNPACK_SEQUENCE',
]

EXECUTE_OPS = [
    'BINARY_OP',
    'BINARY_SLICE',
    'BUILD_LIST',
    'BUILD_MAP',
    'BUILD_SET',
    'BUILD_TUPLE',
    'CALL_FUNCTION_EX',
    'CALL_INTRINSIC_1',
    'CALL_KW',
    'CHECK_EXC_MATCH',
    'COMPARE_OP',
    'CONTAINS_OP',
    'COPY',
    'COPY_FREE_VARS',
    'DELETE_ATTR',
    'DELETE_FAST',
    'DELETE_SUBSCR',
    'END_FOR',
    'FORMAT_SIMPLE',
    'FOR_ITER',
    'GET_ITER',
    'IS_OP',
    'JUMP_BACKWARD',
    'JUMP_FORWARD',
    'LIST_APPEND',
    'LIST_EXTEND',
    'LOAD_ATTR',
    'LOAD_CONST',
    'LOAD_DEREF',
    'LOAD_FAST',
    'LOAD_FAST_AND_CLEAR',
    'LOAD_FAST_BORROW',
    'LOAD_FAST_BORROW_LOAD_FAST_BORROW',
    'LOAD_FAST_CHECK',
    'LOAD_FAST_LOAD_FAST',
    'LOAD_GLOBAL',
    'LOAD_NAME',
    'LOAD_SMALL_INT',
    'MAKE_CELL',
    'NOP',
    'NOT_TAKEN',
    'POP_EXCEPT',
    'POP_ITER',
    'POP_JUMP_IF_FALSE',
    'POP_JUMP_IF_NONE',
    'POP_JUMP_IF_NOT_NONE',
    'POP_JUMP_IF_TRUE',
    'POP_TOP',
    'PUSH_EXC_INFO',
    'PUSH_NULL',
    'RERAISE',
    'RETURN_VALUE',
    'SET_ADD',
    'SET_FUNCTION_ATTRIBUTE',
    'SET_UPDATE',
    'STORE_ATTR',
    'STORE_DEREF',
    'STORE_FAST',
    'STORE_FAST_LOAD_FAST',
    'STORE_FAST_STORE_FAST',
    'STORE_GLOBAL',
    'STORE_NAME',
    'STORE_SUBSCR',
    'SWAP',
    'TO_BOOL',
    'UNARY_INVERT',
    'UNARY_NEGATIVE',
    'UNARY_NOT',
    'UNPACK_EX',
    'UNPACK_SEQUENCE',
]

KEYWORDS = {
    'False': 1,
    'None': 1,
    'True': 1,
    'and': 1,
    'as': 1,
    'assert': 1,
    'async': 1,
    'await': 1,
    'break': 1,
    'class': 1,
    'continue': 1,
    'def': 1,
    'del': 1,
    'elif': 1,
    'else': 1,
    'except': 1,
    'finally': 1,
    'for': 1,
    'from': 1,
    'global': 1,
    'if': 1,
    'import': 1,
    'in': 1,
    'is': 1,
    'lambda': 1,
    'nonlocal': 1,
    'not': 1,
    'or': 1,
    'pass': 1,
    'raise': 1,
    'return': 1,
    'try': 1,
    'while': 1,
    'with': 1,
    'yield': 1,
}

TOK_ENDMARKER = 0
TOK_NAME = 1
TOK_NUMBER = 2
TOK_STRING = 3
TOK_NEWLINE = 4
TOK_INDENT = 5
TOK_DEDENT = 6
TOK_LPAR = 7
TOK_RPAR = 8
TOK_LSQB = 9
TOK_RSQB = 10
TOK_COLON = 11
TOK_COMMA = 12
TOK_SEMI = 13
TOK_PLUS = 14
TOK_MINUS = 15
TOK_STAR = 16
TOK_SLASH = 17
TOK_VBAR = 18
TOK_AMPER = 19
TOK_LESS = 20
TOK_GREATER = 21
TOK_EQUAL = 22
TOK_DOT = 23
TOK_PERCENT = 24
TOK_LBRACE = 25
TOK_RBRACE = 26
TOK_EQEQUAL = 27
TOK_NOTEQUAL = 28
TOK_LESSEQUAL = 29
TOK_GREATEREQUAL = 30
TOK_TILDE = 31
TOK_CIRCUMFLEX = 32
TOK_LEFTSHIFT = 33
TOK_RIGHTSHIFT = 34
TOK_DOUBLESTAR = 35
TOK_PLUSEQUAL = 36
TOK_MINEQUAL = 37
TOK_STAREQUAL = 38
TOK_SLASHEQUAL = 39
TOK_PERCENTEQUAL = 40
TOK_AMPEREQUAL = 41
TOK_VBAREQUAL = 42
TOK_CIRCUMFLEXEQUAL = 43
TOK_LEFTSHIFTEQUAL = 44
TOK_RIGHTSHIFTEQUAL = 45
TOK_DOUBLESTAREQUAL = 46
TOK_DOUBLESLASH = 47
TOK_DOUBLESLASHEQUAL = 48
TOK_AT = 49
TOK_ATEQUAL = 50
TOK_RARROW = 51
TOK_ELLIPSIS = 52
TOK_COLONEQUAL = 53
TOK_EXCLAMATION = 54
TOK_OP = 55
TOK_TYPE_IGNORE = 56
TOK_TYPE_COMMENT = 57
TOK_SOFT_KEYWORD = 58
TOK_FSTRING_START = 59
TOK_FSTRING_MIDDLE = 60
TOK_FSTRING_END = 61
TOK_TSTRING_START = 62
TOK_TSTRING_MIDDLE = 63
TOK_TSTRING_END = 64
TOK_COMMENT = 65
TOK_NL = 66
TOK_ERRORTOKEN = 67
TOK_ENCODING = 68
TOK_N_TOKENS = 69

OP3 = {
    '**=': 1,
    '...': 1,
    '//=': 1,
    '<<=': 1,
    '>>=': 1,
}

OP2 = {
    '!=': 1,
    '%=': 1,
    '&=': 1,
    '**': 1,
    '*=': 1,
    '+=': 1,
    '-=': 1,
    '->': 1,
    '//': 1,
    '/=': 1,
    ':=': 1,
    '<<': 1,
    '<=': 1,
    '==': 1,
    '>=': 1,
    '>>': 1,
    '@=': 1,
    '^=': 1,
    '|=': 1,
}

ND_ADD = 1
ND_AND = 2
ND_ANNASSIGN = 3
ND_ASSERT = 4
ND_ASSIGN = 5
ND_ASYNCFOR = 6
ND_ASYNCFUNCTIONDEF = 7
ND_ASYNCWITH = 8
ND_ATTRIBUTE = 9
ND_AUGASSIGN = 10
ND_AUGLOAD = 11
ND_AUGSTORE = 12
ND_AWAIT = 13
ND_BINOP = 14
ND_BITAND = 15
ND_BITOR = 16
ND_BITXOR = 17
ND_BOOLOP = 18
ND_BREAK = 19
ND_CALL = 20
ND_CLASSDEF = 21
ND_COMPARE = 22
ND_CONSTANT = 23
ND_CONTINUE = 24
ND_DEL = 25
ND_DELETE = 26
ND_DICT = 27
ND_DICTCOMP = 28
ND_DIV = 29
ND_EQ = 30
ND_EXCEPTHANDLER = 31
ND_EXPR = 32
ND_EXPRESSION = 33
ND_EXTSLICE = 34
ND_FLOORDIV = 35
ND_FOR = 36
ND_FORMATTEDVALUE = 37
ND_FUNCTIONDEF = 38
ND_FUNCTIONTYPE = 39
ND_GENERATOREXP = 40
ND_GLOBAL = 41
ND_GT = 42
ND_GTE = 43
ND_IF = 44
ND_IFEXP = 45
ND_IMPORT = 46
ND_IMPORTFROM = 47
ND_IN = 48
ND_INDEX = 49
ND_INTERACTIVE = 50
ND_INTERPOLATION = 51
ND_INVERT = 52
ND_IS = 53
ND_ISNOT = 54
ND_JOINEDSTR = 55
ND_LSHIFT = 56
ND_LAMBDA = 57
ND_LIST = 58
ND_LISTCOMP = 59
ND_LOAD = 60
ND_LT = 61
ND_LTE = 62
ND_MATMULT = 63
ND_MATCH = 64
ND_MATCHAS = 65
ND_MATCHCLASS = 66
ND_MATCHMAPPING = 67
ND_MATCHOR = 68
ND_MATCHSEQUENCE = 69
ND_MATCHSINGLETON = 70
ND_MATCHSTAR = 71
ND_MATCHVALUE = 72
ND_MOD = 73
ND_MODULE = 74
ND_MULT = 75
ND_NAME = 76
ND_NAMEDEXPR = 77
ND_NONLOCAL = 78
ND_NOT = 79
ND_NOTEQ = 80
ND_NOTIN = 81
ND_OR = 82
ND_PARAM = 83
ND_PARAMSPEC = 84
ND_PASS = 85
ND_POW = 86
ND_RSHIFT = 87
ND_RAISE = 88
ND_RETURN = 89
ND_SET = 90
ND_SETCOMP = 91
ND_SLICE = 92
ND_STARRED = 93
ND_STORE = 94
ND_SUB = 95
ND_SUBSCRIPT = 96
ND_SUITE = 97
ND_TEMPLATESTR = 98
ND_TRY = 99
ND_TRYSTAR = 100
ND_TUPLE = 101
ND_TYPEALIAS = 102
ND_TYPEIGNORE = 103
ND_TYPEVAR = 104
ND_TYPEVARTUPLE = 105
ND_UADD = 106
ND_USUB = 107
ND_UNARYOP = 108
ND_WHILE = 109
ND_WITH = 110
ND_YIELD = 111
ND_YIELDFROM = 112
ND_ALIAS = 113
ND_ARG = 114
ND_ARGUMENTS = 115
ND_COMPREHENSION = 116
ND_KEYWORD = 117
ND_MATCH_CASE = 118
ND_WITHITEM = 119
ND_N_KINDS = 119

ND = {
    'Add': 1,
    'And': 2,
    'AnnAssign': 3,
    'Assert': 4,
    'Assign': 5,
    'AsyncFor': 6,
    'AsyncFunctionDef': 7,
    'AsyncWith': 8,
    'Attribute': 9,
    'AugAssign': 10,
    'AugLoad': 11,
    'AugStore': 12,
    'Await': 13,
    'BinOp': 14,
    'BitAnd': 15,
    'BitOr': 16,
    'BitXor': 17,
    'BoolOp': 18,
    'Break': 19,
    'Call': 20,
    'ClassDef': 21,
    'Compare': 22,
    'Constant': 23,
    'Continue': 24,
    'Del': 25,
    'Delete': 26,
    'Dict': 27,
    'DictComp': 28,
    'Div': 29,
    'Eq': 30,
    'ExceptHandler': 31,
    'Expr': 32,
    'Expression': 33,
    'ExtSlice': 34,
    'FloorDiv': 35,
    'For': 36,
    'FormattedValue': 37,
    'FunctionDef': 38,
    'FunctionType': 39,
    'GeneratorExp': 40,
    'Global': 41,
    'Gt': 42,
    'GtE': 43,
    'If': 44,
    'IfExp': 45,
    'Import': 46,
    'ImportFrom': 47,
    'In': 48,
    'Index': 49,
    'Interactive': 50,
    'Interpolation': 51,
    'Invert': 52,
    'Is': 53,
    'IsNot': 54,
    'JoinedStr': 55,
    'LShift': 56,
    'Lambda': 57,
    'List': 58,
    'ListComp': 59,
    'Load': 60,
    'Lt': 61,
    'LtE': 62,
    'MatMult': 63,
    'Match': 64,
    'MatchAs': 65,
    'MatchClass': 66,
    'MatchMapping': 67,
    'MatchOr': 68,
    'MatchSequence': 69,
    'MatchSingleton': 70,
    'MatchStar': 71,
    'MatchValue': 72,
    'Mod': 73,
    'Module': 74,
    'Mult': 75,
    'Name': 76,
    'NamedExpr': 77,
    'Nonlocal': 78,
    'Not': 79,
    'NotEq': 80,
    'NotIn': 81,
    'Or': 82,
    'Param': 83,
    'ParamSpec': 84,
    'Pass': 85,
    'Pow': 86,
    'RShift': 87,
    'Raise': 88,
    'Return': 89,
    'Set': 90,
    'SetComp': 91,
    'Slice': 92,
    'Starred': 93,
    'Store': 94,
    'Sub': 95,
    'Subscript': 96,
    'Suite': 97,
    'TemplateStr': 98,
    'Try': 99,
    'TryStar': 100,
    'Tuple': 101,
    'TypeAlias': 102,
    'TypeIgnore': 103,
    'TypeVar': 104,
    'TypeVarTuple': 105,
    'UAdd': 106,
    'USub': 107,
    'UnaryOp': 108,
    'While': 109,
    'With': 110,
    'Yield': 111,
    'YieldFrom': 112,
    'alias': 113,
    'arg': 114,
    'arguments': 115,
    'comprehension': 116,
    'keyword': 117,
    'match_case': 118,
    'withitem': 119,
}

BINOPS = {
    '+': 1,
    '-': 95,
    '*': 75,
    '/': 29,
    '//': 35,
    '%': 73,
    '**': 86,
    '<<': 56,
    '>>': 87,
    '|': 16,
    '^': 17,
    '&': 15,
}

UNOPS = {
    '+': 106,
    '-': 107,
    '~': 52,
}

CMPOPS = {
    '==': 30,
    '!=': 80,
    '<': 61,
    '>': 42,
    '<=': 62,
    '>=': 43,
}

PREC = {
    'or': 1,
    'and': 2,
    'not': 3,
    'cmp': 4,
    '|': 5,
    '^': 6,
    '&': 7,
    '<<': 8,
    '>>': 8,
    '+': 9,
    '-': 9,
    '*': 10,
    '/': 10,
    '//': 10,
    '%': 10,
    'u': 11,
    '**': 12,
}

RIGHTASSOC = {
    '**': 1,
}
