# Generated by pycore/tools/gen_compiler_tables.py from
# pycore/targets/pycore.json and the host opcode/keyword/token modules.
# Do not edit. CI: pycore/tests/test_compiler_tables_fresh.py

OPMAP = {
    'BINARY_OP': 44,
    'BINARY_SLICE': 1,
    'BUILD_LIST': 46,
    'BUILD_MAP': 47,
    'BUILD_SET': 48,
    'BUILD_STRING': 50,
    'BUILD_TUPLE': 51,
    'CACHE': 0,
    'CALL': 52,
    'CALL_FUNCTION_EX': 4,
    'CALL_INTRINSIC_1': 53,
    'CALL_KW': 55,
    'CHECK_EXC_MATCH': 6,
    'COMPARE_OP': 56,
    'CONTAINS_OP': 57,
    'CONVERT_VALUE': 58,
    'COPY': 59,
    'DELETE_ATTR': 61,
    'DELETE_FAST': 63,
    'DELETE_SUBSCR': 8,
    'DICT_MERGE': 66,
    'DICT_UPDATE': 67,
    'END_FOR': 9,
    'EXTENDED_ARG': 69,
    'FORMAT_SIMPLE': 12,
    'FOR_ITER': 70,
    'GET_ITER': 16,
    'IS_OP': 74,
    'JUMP_BACKWARD': 75,
    'JUMP_FORWARD': 77,
    'LIST_APPEND': 78,
    'LIST_EXTEND': 79,
    'LOAD_ATTR': 80,
    'LOAD_CONST': 82,
    'LOAD_FAST': 84,
    'LOAD_FAST_AND_CLEAR': 85,
    'LOAD_FAST_BORROW': 86,
    'LOAD_FAST_BORROW_LOAD_FAST_BORROW': 87,
    'LOAD_FAST_CHECK': 88,
    'LOAD_FAST_LOAD_FAST': 89,
    'LOAD_GLOBAL': 92,
    'LOAD_NAME': 93,
    'LOAD_SMALL_INT': 94,
    'MAKE_FUNCTION': 23,
    'MAP_ADD': 98,
    'NOP': 27,
    'NOT_TAKEN': 28,
    'POP_EXCEPT': 29,
    'POP_ITER': 30,
    'POP_JUMP_IF_FALSE': 100,
    'POP_JUMP_IF_NONE': 101,
    'POP_JUMP_IF_NOT_NONE': 102,
    'POP_JUMP_IF_TRUE': 103,
    'POP_TOP': 31,
    'PUSH_EXC_INFO': 32,
    'PUSH_NULL': 33,
    'RAISE_VARARGS': 104,
    'RERAISE': 105,
    'RESUME': 128,
    'RETURN_VALUE': 35,
    'SET_ADD': 107,
    'SET_UPDATE': 109,
    'STORE_ATTR': 110,
    'STORE_FAST': 112,
    'STORE_FAST_LOAD_FAST': 113,
    'STORE_FAST_STORE_FAST': 114,
    'STORE_GLOBAL': 115,
    'STORE_NAME': 116,
    'STORE_SUBSCR': 38,
    'SWAP': 117,
    'TO_BOOL': 39,
    'UNARY_INVERT': 40,
    'UNARY_NEGATIVE': 41,
    'UNARY_NOT': 42,
    'UNPACK_EX': 118,
    'UNPACK_SEQUENCE': 119,
}

EMIT_OPS = [
    'BINARY_OP',
    'BINARY_SLICE',
    'BUILD_LIST',
    'BUILD_MAP',
    'BUILD_SET',
    'BUILD_STRING',
    'BUILD_TUPLE',
    'CACHE',
    'CALL',
    'CALL_FUNCTION_EX',
    'CALL_INTRINSIC_1',
    'CALL_KW',
    'CHECK_EXC_MATCH',
    'COMPARE_OP',
    'CONTAINS_OP',
    'CONVERT_VALUE',
    'COPY',
    'DELETE_ATTR',
    'DELETE_FAST',
    'DELETE_SUBSCR',
    'DICT_MERGE',
    'DICT_UPDATE',
    'END_FOR',
    'EXTENDED_ARG',
    'FORMAT_SIMPLE',
    'FOR_ITER',
    'GET_ITER',
    'IS_OP',
    'JUMP_BACKWARD',
    'JUMP_FORWARD',
    'LIST_APPEND',
    'LIST_EXTEND',
    'LOAD_ATTR',
    'LOAD_CONST',
    'LOAD_FAST',
    'LOAD_FAST_AND_CLEAR',
    'LOAD_FAST_BORROW',
    'LOAD_FAST_BORROW_LOAD_FAST_BORROW',
    'LOAD_FAST_CHECK',
    'LOAD_FAST_LOAD_FAST',
    'LOAD_GLOBAL',
    'LOAD_NAME',
    'LOAD_SMALL_INT',
    'MAKE_FUNCTION',
    'MAP_ADD',
    'NOP',
    'NOT_TAKEN',
    'POP_EXCEPT',
    'POP_ITER',
    'POP_JUMP_IF_FALSE',
    'POP_JUMP_IF_NONE',
    'POP_JUMP_IF_NOT_NONE',
    'POP_JUMP_IF_TRUE',
    'POP_TOP',
    'PUSH_EXC_INFO',
    'PUSH_NULL',
    'RAISE_VARARGS',
    'RERAISE',
    'RESUME',
    'RETURN_VALUE',
    'SET_ADD',
    'SET_UPDATE',
    'STORE_ATTR',
    'STORE_FAST',
    'STORE_FAST_LOAD_FAST',
    'STORE_FAST_STORE_FAST',
    'STORE_GLOBAL',
    'STORE_NAME',
    'STORE_SUBSCR',
    'SWAP',
    'TO_BOOL',
    'UNARY_INVERT',
    'UNARY_NEGATIVE',
    'UNARY_NOT',
    'UNPACK_EX',
    'UNPACK_SEQUENCE',
]

EXECUTE_OPS = [
    'BINARY_OP',
    'BINARY_SLICE',
    'BUILD_LIST',
    'BUILD_MAP',
    'BUILD_SET',
    'BUILD_TUPLE',
    'CALL_FUNCTION_EX',
    'CALL_INTRINSIC_1',
    'CALL_KW',
    'CHECK_EXC_MATCH',
    'COMPARE_OP',
    'CONTAINS_OP',
    'COPY',
    'DELETE_ATTR',
    'DELETE_FAST',
    'DELETE_SUBSCR',
    'END_FOR',
    'FORMAT_SIMPLE',
    'FOR_ITER',
    'GET_ITER',
    'IS_OP',
    'JUMP_BACKWARD',
    'JUMP_FORWARD',
    'LIST_APPEND',
    'LIST_EXTEND',
    'LOAD_ATTR',
    'LOAD_CONST',
    'LOAD_FAST',
    'LOAD_FAST_AND_CLEAR',
    'LOAD_FAST_BORROW',
    'LOAD_FAST_BORROW_LOAD_FAST_BORROW',
    'LOAD_FAST_CHECK',
    'LOAD_FAST_LOAD_FAST',
    'LOAD_GLOBAL',
    'LOAD_NAME',
    'LOAD_SMALL_INT',
    'NOP',
    'NOT_TAKEN',
    'POP_EXCEPT',
    'POP_ITER',
    'POP_JUMP_IF_FALSE',
    'POP_JUMP_IF_NONE',
    'POP_JUMP_IF_NOT_NONE',
    'POP_JUMP_IF_TRUE',
    'POP_TOP',
    'PUSH_EXC_INFO',
    'PUSH_NULL',
    'RERAISE',
    'RETURN_VALUE',
    'SET_ADD',
    'SET_UPDATE',
    'STORE_ATTR',
    'STORE_FAST',
    'STORE_FAST_LOAD_FAST',
    'STORE_FAST_STORE_FAST',
    'STORE_GLOBAL',
    'STORE_NAME',
    'STORE_SUBSCR',
    'SWAP',
    'TO_BOOL',
    'UNARY_INVERT',
    'UNARY_NEGATIVE',
    'UNARY_NOT',
    'UNPACK_EX',
    'UNPACK_SEQUENCE',
]

KEYWORDS = {
    'False': 1,
    'None': 1,
    'True': 1,
    'and': 1,
    'as': 1,
    'assert': 1,
    'async': 1,
    'await': 1,
    'break': 1,
    'class': 1,
    'continue': 1,
    'def': 1,
    'del': 1,
    'elif': 1,
    'else': 1,
    'except': 1,
    'finally': 1,
    'for': 1,
    'from': 1,
    'global': 1,
    'if': 1,
    'import': 1,
    'in': 1,
    'is': 1,
    'lambda': 1,
    'nonlocal': 1,
    'not': 1,
    'or': 1,
    'pass': 1,
    'raise': 1,
    'return': 1,
    'try': 1,
    'while': 1,
    'with': 1,
    'yield': 1,
}

TOK_ENDMARKER = 0
TOK_NAME = 1
TOK_NUMBER = 2
TOK_STRING = 3
TOK_NEWLINE = 4
TOK_INDENT = 5
TOK_DEDENT = 6
TOK_LPAR = 7
TOK_RPAR = 8
TOK_LSQB = 9
TOK_RSQB = 10
TOK_COLON = 11
TOK_COMMA = 12
TOK_SEMI = 13
TOK_PLUS = 14
TOK_MINUS = 15
TOK_STAR = 16
TOK_SLASH = 17
TOK_VBAR = 18
TOK_AMPER = 19
TOK_LESS = 20
TOK_GREATER = 21
TOK_EQUAL = 22
TOK_DOT = 23
TOK_PERCENT = 24
TOK_LBRACE = 25
TOK_RBRACE = 26
TOK_EQEQUAL = 27
TOK_NOTEQUAL = 28
TOK_LESSEQUAL = 29
TOK_GREATEREQUAL = 30
TOK_TILDE = 31
TOK_CIRCUMFLEX = 32
TOK_LEFTSHIFT = 33
TOK_RIGHTSHIFT = 34
TOK_DOUBLESTAR = 35
TOK_PLUSEQUAL = 36
TOK_MINEQUAL = 37
TOK_STAREQUAL = 38
TOK_SLASHEQUAL = 39
TOK_PERCENTEQUAL = 40
TOK_AMPEREQUAL = 41
TOK_VBAREQUAL = 42
TOK_CIRCUMFLEXEQUAL = 43
TOK_LEFTSHIFTEQUAL = 44
TOK_RIGHTSHIFTEQUAL = 45
TOK_DOUBLESTAREQUAL = 46
TOK_DOUBLESLASH = 47
TOK_DOUBLESLASHEQUAL = 48
TOK_AT = 49
TOK_ATEQUAL = 50
TOK_RARROW = 51
TOK_ELLIPSIS = 52
TOK_COLONEQUAL = 53
TOK_EXCLAMATION = 54
TOK_OP = 55
TOK_TYPE_IGNORE = 56
TOK_TYPE_COMMENT = 57
TOK_SOFT_KEYWORD = 58
TOK_FSTRING_START = 59
TOK_FSTRING_MIDDLE = 60
TOK_FSTRING_END = 61
TOK_TSTRING_START = 62
TOK_TSTRING_MIDDLE = 63
TOK_TSTRING_END = 64
TOK_COMMENT = 65
TOK_NL = 66
TOK_ERRORTOKEN = 67
TOK_ENCODING = 68
TOK_N_TOKENS = 69

OP3 = {
    '**=': 1,
    '...': 1,
    '//=': 1,
    '<<=': 1,
    '>>=': 1,
}

OP2 = {
    '!=': 1,
    '%=': 1,
    '&=': 1,
    '**': 1,
    '*=': 1,
    '+=': 1,
    '-=': 1,
    '->': 1,
    '//': 1,
    '/=': 1,
    ':=': 1,
    '<<': 1,
    '<=': 1,
    '==': 1,
    '>=': 1,
    '>>': 1,
    '@=': 1,
    '^=': 1,
    '|=': 1,
}
