`include "pycore_defs.svh"

// Writable code memory (Plan 1 P1).  Same 64-bit slot geometry as pycore_imem
// but READ_ONLY(0), so runtime-loaded or runtime-generated bytecode can be
// placed here and fetched.  Addresses are relative to this bank; the region mux
// in pycore_code_mem subtracts PYCORE_CODE_RAM_BYTE_BASE before driving it.
//
// INIT_HEX is test-only: it lets an image preload code RAM before any loader
// exists.  Production images leave it empty and fill the bank at runtime.
module pycore_code_ram #(
    parameter int    ADDR_WIDTH  = PYCORE_ADDR_WIDTH,
    parameter int    DATA_WIDTH  = PYCORE_IMEM_DATA_WIDTH,
    parameter int    BLOCK_SHIFT = PYCORE_BLOCK_SHIFT,
    parameter int    BLOCK_COUNT = PYCORE_CODE_RAM_BLOCK_COUNT,
    parameter string INIT_HEX    = ""
) (
    input  logic                  clk_i,
    input  logic                  rst_n_i,
    input  logic                  req_i,
    input  logic                  we_i,
    input  logic [ADDR_WIDTH-1:0] addr_i,
    input  logic [DATA_WIDTH-1:0] wdata_i,
    output logic                  ack_o,
    output logic [DATA_WIDTH-1:0] rdata_o,
    output logic                  fault_o
);

    pycore_mem_bank #(
        .DATA_WIDTH(DATA_WIDTH),
        .ADDR_WIDTH(ADDR_WIDTH),
        .BLOCK_SHIFT(BLOCK_SHIFT),
        .BLOCK_COUNT(BLOCK_COUNT),
        .READ_ONLY(0),
        .INIT_HEX(INIT_HEX)
    ) bank (
        .clk_i(clk_i),
        .rst_n_i(rst_n_i),
        .req_i(req_i),
        .we_i(we_i),
        .addr_i(addr_i),
        .wdata_i(wdata_i),
        .ack_o(ack_o),
        .rdata_o(rdata_o),
        .fault_o(fault_o)
    );

endmodule
